### ISSUE TITLE
z_source

### ISSUE THREAD

**Issue by dsluse** [SSingh087/seq-pred#2]
In the code you post, z_source=0.02 < z_lens=0.05. This does not make much sense and I wonder how you can get any sensible result following this approach. The arxiv paper https://arxiv.org/abs/2012.15476 does suggest that this is not a typo ... unless I mis-understood what you are doing.

**Comment by SSingh087** [comment]
@dsluse Thank you for highlighting this issue; what I meant specifically in the case of **merging galaxies** that the **merger plane**, which acts as the source, has a redshift of z = 0.02, and the lens, which in our case is the galaxy has z=0.05. However, the point is valid for **mono-galaxies** (not mergers). 
Below I have posted the result for merging galaxies with z_source =0.02 and 0.08, keeping z_lens =0.05 
![z_source =0.02](https://user-images.githubusercontent.com/66710757/104090031-b714ce00-5299-11eb-9e03-2d1884a6dc61.gif)
![z_source =0.08](https://user-images.githubusercontent.com/66710757/104090184-d06a4a00-529a-11eb-928f-937d772f07c2.gif)
So I aimed to observe how the gravitational lens would evolve in merging galaxies and mono galaxies. I have also attached a wiki-image https://upload.wikimedia.org/wikipedia/commons/0/03/Imageedit_6_2578820362.gif for reference to what I intended to do.

**Comment by dsluse** [comment]
@SSingh087 It is correct that you can work with angular scales only without fixing the redshift. You may need the later to turn this into a physical problem (i.e. turn angular length into physical length ; derive a lens mass). In any case, it does not make any sense to have a z_source < z_lens (or you should call your source a lens and vice versa). On the other hand, you may not have any galaxy able to produce strong lensing with such a small difference of redshift. This may indeed be indicated by the mass you quote for the lens in your paper: 10^15 M_sun ... this is a galaxy cluster mass, not a galaxy mass. My 2 cents.

**Comment by SSingh087** [comment]
Yes I'll highlight the issue in the code
